name: Tests

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          # 0.12.30-latest
          - TERRAFORM_VERSION: "0.12.30"
            TFCODING_DOCKER_TAG: "unfor19/tfcoding:0.12.30-latest"
          # 0.13.6-latest
          - TERRAFORM_VERSION: "0.13.6"
            TFCODING_DOCKER_TAG: "unfor19/tfcoding:0.13.6-latest"
          # 0.14.8-latest
          - TERRAFORM_VERSION: "0.14.8"
            TFCODING_DOCKER_TAG: "unfor19/tfcoding:0.14.8-latest"
          # 0.15.0-beta2
          - TERRAFORM_VERSION: "0.15.0-beta2"
            TFCODING_DOCKER_TAG: "unfor19/tfcoding:0.15.0-beta2-latest"
          # 1.0.6
          - TERRAFORM_VERSION: "1.0.6"
            TFCODING_DOCKER_TAG: "unfor19/tfcoding:1.0.6-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Tests Terraform Version - ${{ matrix.TERRAFORM_VERSION }}
        env:
          TFCODING_DOCKER_TAG: ${{ matrix.TFCODING_DOCKER_TAG }}
        run: |
          ./scripts/tests.sh
